### ISSUE TITLE
Dictionary as standalone HTML

### ISSUE THREAD

**Issue by dhdaines** [MotherTongues/mothertongues#17]
Similar to ReadAlong Studio, it would be really neat if we could produce a basic dictionary that lives in a single file and does not require a horde of `node_modules` and a server to view.

I don't know if this is this is possible to do with a Modern Reactive Java Script Framework™ since one cannot do HTML5 routing, for instance, but it really doesn't need to be fancy, especially if a somewhat HTML/CSS-savvy user could style it to their liking.

**Comment by roedoejet** [comment]
I'm hesitant to support this because I think for anything other than a trivially small dictionary, the file size would be prohibitively large. I think I'd rather just continue supporting an easy way to deploy MTD (via GitHub Pages or Netlify + a starter repo). And the UIs should already both support downloading for offline use (following an initial connection to the site). Is there another use case I'm not thinking of here though?
